name: Deploy

on:
  push:
    branches:
     - main
      #- gh-pages

permissions:
  contents: write  # Give write access to repository contents
  pages: write     # Allow deployment to GitHub Pages

jobs:
  build_and_predeploy:
    name: Build and Predeploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean npm cache and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install dependencies (with npm ci)
        run: npm ci

      # - name: Install dependencies
      #   run: npm install
        #uses: bahmutov/npm-install@v1

      - name: Build and predeploy project
        run: npm run predeploy

      - name: List contents of dist folder for debugging
        run: |
          echo "Listing contents of the dist directory..."
          ls -al dist  # This will show the files in the 'dist' directory

      # - name: Deploy to Github Pages
      #   run: npx gh-pages -d dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        run: |
          # Set up Git user info
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Debugging: List current branch and remote configuration
          git branch -a
          git remote -v
          
          # Use the GITHUB_TOKEN to authenticate the git push
          npx gh-pages -d dist -b gh-pages --repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Upload production-ready build files
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: production-files-ubuntu-latest
  #         path: ./dist

  # deploy:
  #   name: Deploy
  #   needs: build_and_predeploy
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: production-files-*
  #         path: ./dist
  #         merge-multiple: true

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist